<?php

namespace Alex\ChatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUsersOnline($timeOnline)
    {
        $query = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->select('u')
            ->from('ChatBundle:User', 'u')
            ->where('u.lastOnline > :timeOnline')
            ->setParameter('timeOnline', $timeOnline);
        $query = $query->getQuery()->getResult();
        return $query;
    }
}
